In [1]:
import numpy as np

Create an array 

In [26]:
x = np.array([5,1])
x

array([5, 1])

Addition

In [4]:
x+1

array([6, 2])

Multiplication

In [5]:
x*5

array([25,  5])

In [6]:
y = np.array([4,7])

In [7]:
x+y

array([9, 8])

In [8]:
x*y

array([20,  7])

Create a zero matrix

In [9]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create a ones matrix

In [10]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create a random matrix [rows,columns]

In [11]:
np.random.random([3,2])

array([[0.55896881, 0.39382872],
       [0.81796936, 0.61448975],
       [0.80744323, 0.99179085]])

In [27]:
x = np.array([3,5])
x

array([3, 5])

In [15]:
x.shape

(2,)

In [18]:
y = np.array([[3,4,3],[4,2,3]])

In [19]:
y

array([[3, 4, 3],
       [4, 2, 3]])

In [20]:
y.shape

(2, 3)

Transpose

In [21]:
y.transpose()

array([[3, 4],
       [4, 2],
       [3, 3]])

In [24]:
z = y.transpose()
z

array([[3, 4],
       [4, 2],
       [3, 3]])

In [28]:
z.shape

(3, 2)

In [29]:
y

array([[3, 4, 3],
       [4, 2, 3]])

In [31]:
z = y+3
z

array([[6, 7, 6],
       [7, 5, 6]])

Element wise multiplication 

In [32]:
z*y

array([[18, 28, 18],
       [28, 10, 18]])

Linear algebra multiplication

In [ ]:
np.matmul(x,z)

In [33]:
np.exp(x)

array([ 20.08553692, 148.4131591 ])

In [34]:
np.sin(x)

array([ 0.14112001, -0.95892427])

In [35]:
np.cos(x)

array([-0.9899925 ,  0.28366219])

In [36]:
np.tanh(x)

array([0.99505475, 0.9999092 ])

Write a function called operations that takes as input two positive integers h and w, makes two random matrices A and B, of size h x w, and returns A,B, and s, the sum of A and B.

In [40]:
def operations(h,w):


    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B

    return A,B,s


In [45]:
np.max(x)

5

In [46]:
np.min(x)

3

In [47]:
x.max()

5

In [48]:
x.min()

3

In [49]:
np.random.random([2,1])

array([[0.29028294],
       [0.87704254]])

In [50]:
np.random.random()

0.08789734950308525

In [51]:
np.linalg.norm(x)

5.830951894845301